# 메인 설정 파일

spring:
  application:
    name: backend

  profiles:
    active: dev


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        # 엔티티 필드명 그대로 DB 컬럼명(카멜케이스, 언더스코어 변환 없음)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # 1. 설정 임포트 (외부 설정 파일 불러오기)
  config:
    import:
        - classpath:application-secret.yaml  # optional 제거
        - classpath:application-mail.yaml    # optional 제거


# Swagger UI 활성화
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true




  # 2. 이메일 발송용 설정


# 4. 기타 설정 (spring 블록 밖)
custom:
  cookie:
    secure: ${COOKIE_SECURE:true} # 환경 변수가 없으면 기본값 true